// ═══════════════════════════════════════════════════════════════
// LUA EXPORT - Generate Lua code for DisplayLib
// ═══════════════════════════════════════════════════════════════

// Генерация Lua кода из текущего состояния canvas
function generateLua() {
  const { widgets, background } = window.ScreenGenerator;
  const screenId = document.getElementById('screenId').value || 'my_screen';
  
  const lines = [];
  
  // Заголовок
  lines.push('-- DisplayLib Screen Configuration');
  lines.push('-- Generated by DisplayLib Screen Generator');
  lines.push('');
  
  // Импорты
  lines.push('local DisplayLib = require("DisplayLib")');
  lines.push('');
  
  // Создание экрана
  lines.push(`local screen = DisplayLib.newScreen("${screenId}")`);
  lines.push('');
  
  // Фон
  if (background) {
    lines.push('-- Background');
    lines.push('screen:setBackground({');
    lines.push(`    color = {${background.colorHex.slice(1).match(/.{2}/g).map(hex => parseInt(hex, 16)).join(', ')}},`);
    lines.push(`    alpha = ${background.alpha},`);
    lines.push(`    scale = {${background.w * 8}, ${background.h * 4}, 1},`);
    lines.push(`    position = {${background.posX}, ${background.posY}, 0},`);
    lines.push(`    translation = {${background.transX}, ${background.transY}, ${background.transZ || 0}}`);
    lines.push('})');
    lines.push('');
  }
  
  // Виджеты
  if (widgets.length > 0) {
    lines.push('-- Widgets');
    
    for (const w of widgets) {
      const isText = w.type === 'TEXT_BUTTON';
      
      lines.push(`-- ${w.id}`);
      
      if (isText) {
        // TEXT_BUTTON
        lines.push(`screen:addTextButton("${w.id}", {`);
        lines.push(`    text = "${w.text || ''}",`);
        if (w.hoveredText) {
          lines.push(`    hoveredText = "${w.hoveredText}",`);
        }
        lines.push(`    scale = {${w.w * 8}, ${w.h * 4}, 1},`);
        lines.push(`    position = {${w.x}, ${w.y}, 0},`);
        lines.push(`    translation = {${w.transX || 0}, ${w.transY || 0}, ${w.transZ || 0}},`);
        
        if (w.backgroundColor) {
          lines.push(`    backgroundColor = {${w.backgroundColor.join(', ')}},`);
        }
        if (w.backgroundAlpha !== undefined) {
          lines.push(`    backgroundAlpha = ${w.backgroundAlpha},`);
        }
        
        lines.push(`    tolerance = {${w.tolerance.join(', ')}},`);
        lines.push(`    onClick = {`);
        lines.push(`        action = "${w.onClick}"`);
        lines.push(`    }`);
        lines.push('})');
        
      } else {
        // ITEM_BUTTON
        lines.push(`screen:addItemButton("${w.id}", {`);
        lines.push(`    material = "${w.material}",`);
        lines.push(`    scale = {${w.w}, ${w.h}, ${w.w}},`);
        lines.push(`    position = {${w.x}, ${w.y}, 0},`);
        lines.push(`    translation = {${w.transX || 0}, ${w.transY || 0}, ${w.transZ || 0}},`);
        lines.push(`    tolerance = {${w.tolerance.join(', ')}},`);
        lines.push(`    onClick = {`);
        lines.push(`        action = "${w.onClick}"`);
        lines.push(`    }`);
        lines.push('})');
      }
      
      lines.push('');
    }
  }
  
  // Регистрация экрана
  lines.push('-- Register screen');
  lines.push(`DisplayLib.registerScreen("${screenId}", screen)`);
  lines.push('');
  lines.push('return screen');
  
  return lines.join('\n');
}

// Подсветка Lua перенесена в code-editor.js

// Экспорт функций (только generateLua, подсветка перенесена в code-editor.js)
Object.assign(window.ScreenGenerator, {
  generateLua
});